version: '3'

volumes:
  production_postgres_local_data: {}
  production_postgres_local_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: firefly_import_helpers_postgres_local
    volumes:
      - production_postgres_local_data:/var/lib/postgresql/data:Z
      - production_postgres_local_data_backups:/backups:z
    env_file:
      - ./.local.env
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6380:6379"
