#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/firefly_helper/manage.py collectstatic --noinput

/usr/local/bin/gunicorn firefly_helper.wsgi:application --bind 0.0.0.0:6200 --chdir=/app/firefly_helper