#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/firefly_helper/manage.py migrate



if [ "$DJANGO_SUPERUSER_USERNAME" ]
then
    python /app/firefly_helper/manage.py ensure_adminuser \
        --username=$DJANGO_SUPERUSER_USERNAME \
        --password=$DJANGO_SUPERUSER_PASSWORD
fi

python /app/firefly_helper/manage.py collectstatic --noinput

python /app/firefly_helper/manage.py runserver_plus 127.0.0.1:8999
