# Generated by Django 3.2.15 on 2022-09-30 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axiscreditcardstatements',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='axis_cc_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
