# Generated by Django 3.2.15 on 2022-09-30 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_axiscreditcardstatements_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxisSavingsAccountStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='axis_savings_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
            ],
        ),
        migrations.AddField(
            model_name='axiscreditcardstatements',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='axis_cc_uploads_processed/'),
        ),
        migrations.AddField(
            model_name='axiscreditcardstatements',
            name='status',
            field=models.CharField(blank=True, choices=[('Unprocessed', 'Unprocessed'), ('Processed', 'Processed'), ('Cancelled', 'Cancelled')], default='Unprocessed', max_length=250, null=True),
        ),
    ]
