# Generated by Django 3.2.15 on 2022-09-30 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220930_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='statement_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('status', models.CharField(blank=True, choices=[('Unprocessed', 'Unprocessed'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Unprocessed', max_length=250, null=True)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed_statements/')),
                ('logs', models.TextField(blank=True, null=True)),
                ('statement_type', models.CharField(blank=True, choices=[('Axis CC', 'Axis CC'), ('Axis Savings', 'Axis Savings'), ('ICICI CC', 'ICICI CC'), ('ICICI Savings', 'ICICI Savings'), ('SBI CC', 'SBI CC'), ('SBI Savings', 'SBI Savings')], default=None, max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AxisCreditCardStatements',
        ),
        migrations.DeleteModel(
            name='AxisSavingsAccountStatements',
        ),
    ]
