# Generated by Django 3.2.15 on 2022-09-30 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20220930_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementfile',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='statement_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv'])]),
        ),
    ]
