# Generated by Django 3.2.15 on 2022-09-30 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_statementfile_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(max_length=250)),
                ('product_asin', models.CharField(max_length=250)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonStatementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statement_file', models.FileField(upload_to='amazon_statement_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('status', models.CharField(blank=True, choices=[('Unprocessed', 'Unprocessed'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Unprocessed', max_length=250, null=True)),
            ],
        ),
    ]
