# Generated by Django 3.2.15 on 2022-10-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_files_statementfile_statement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementfile',
            name='statement_type',
            field=models.CharField(blank=True, choices=[('Axis CC', 'Axis CC'), ('Axis Savings', 'Axis Savings'), ('ICICI CC', 'ICICI CC'), ('ICICI Savings', 'ICICI Savings'), ('SBI CC', 'SBI CC'), ('SBI Savings', 'SBI Savings'), ('Amazon Mapping Data', 'Amazon Mapping Data')], default=None, max_length=250, null=True),
        ),
    ]
