# Generated by Django 3.2.15 on 2022-10-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20221001_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonstatementfile',
            name='log_data',
        ),
        migrations.AddField(
            model_name='amazonstatementfile',
            name='log_data',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.ProcessLog'),
        ),
        migrations.RemoveField(
            model_name='statementfile',
            name='log_data',
        ),
        migrations.AddField(
            model_name='statementfile',
            name='log_data',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.ProcessLog'),
        ),
    ]
