# Generated by Django 3.2.15 on 2022-10-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20221001_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateField()),
                ('transaction_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('asset_account', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('amount_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('statement_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.statementfile')),
            ],
        ),
    ]
