# Generated by Django 3.2.15 on 2022-10-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_transactiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Unprocessed'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Unprocessed', max_length=100),
        ),
    ]
