# Generated by Django 3.2.15 on 2022-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_transactiondata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonorderdetail',
            name='order_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
