# Generated by Django 3.2.15 on 2022-10-01 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_amazonorderdetail_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementfile',
            name='statement_file',
            field=models.FileField(blank=True, null=True, upload_to='statement_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'xls'])]),
        ),
    ]
