# Generated by Django 3.2.15 on 2022-10-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_statementfile_statement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondata',
            name='amount_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='amount_debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
