# Generated by Django 3.2.15 on 2022-10-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_rename_product_asin_amazonorderdetail_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorderdetail',
            name='category_list',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='amazonorderdetail',
            name='json_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='amazonorderdetail',
            name='main_category',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='amazonorderdetail',
            name='product_asin',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
