# Generated by Django 3.2.15 on 2022-10-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_amazonorderdetail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonorderdetail',
            old_name='product_asin',
            new_name='product_link',
        ),
    ]
