# Generated by Django 3.2.15 on 2022-10-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_rename_product_asin_amazonorderdetail_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorderdetail',
            name='statement_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.amazonstatementfile'),
        ),
    ]
